### PR TITLE
Update SQL Express Docker File

### PR DESCRIPTION
**Pull request by afinzel**
*\* Tweaks to get this to work on Windows 10
- Updated the image file as microsoft has moved it.
- Create sql directories otherwise build would fail.

### CODE REVIEW

**Comment by StefanScherer** [comment]
There is a Docker image `microsoft/mssql-server-windows-express` from Microsoft at the Docker Hub which seems to be maintained and updated my Microsoft.
- Image: https://hub.docker.com/r/microsoft/mssql-server-windows-express/
- Dockerfile: https://github.com/Microsoft/sql-server-samples/tree/master/samples/manage/windows-containers/mssql-server-2016-express-windows

**Comment by afinzel** [comment]
Thanks but from what I understand you need to be running windows server.  This works with windows 10

**Comment by StefanScherer** [comment]
All Docker images also work on Windows 10, the containers run as HyperV containers.

**Comment by afinzel** [comment]
yep your right.  I have moved to using that.

Thanks

**Pull request closed without merging**
